{% set name = "segtok" %}
{% set version = "1.5.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8ab2dd44245bcbfec25b575dc4618473bbdf2af8c2649698cd5a370f42f3db23

build:
  noarch: python
  number: 0
  entry_points:
    - tokenizer = segtok.tokenizer:main
    - segmenter = segtok.segmenter:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - python
    - regex

test:
  imports:
    - segtok
  commands:
    - tokenizer --help
    - segmenter --help

about:
  home: https://github.com/fnl/segtok
  license: MIT
  license_family: MIT
  # License isn't packaged, track issue here: https://github.com/fnl/segtok/issues/22
  license_file: LICENSE
  summary: sentence segmentation and word tokenization tools
  doc_url: http://fnl.es/segtok-a-segmentation-and-tokenization-library.html
  dev_url: https://github.com/fnl/segtok

extra:
  recipe-maintainers:
    - mxr-conda
    - oblute
    - rluria14
    - ndmaxar
